# Site settings
title: Thinking ... 
email: mafzaal@gmail.com
description: "Personal website of Muhammad Afzaal"
url: "http://polyprogrammer.com"
twitter_username: afzaal_qau
github_username:  mafzaal

# Build settings
markdown: kramdown
permalink: pretty
